### PR TITLE
Nerves ASCII art!

### PR DESCRIPTION
**Pull request by fhunleth**
Here's the new login:

image

I was playing around with JaVe last night. I'm sure that it could be better, but it seems like we HAVE to have something.

### CODE REVIEW

**Comment by fhunleth** [comment]
Here's another idea:

image

**Comment by jjcarstens** [comment]
I also have these I've played with in the past:

image

image

If we're taking votes, I might like the second one you posted the most

**Comment by fhunleth** [comment]
Nice. I was liking the larger ones and then got cold feet since the `iex.exs` already displays a lot. I came to the conclusion that the "N E R V E S" part doesn't look good for anything 2 or 3 lines high. 

Except for the size, I do like your versions. And the colors are better.

The block one (the second one of mine) needs to be cleaned up. I did it super quick and ran out of time. Perhaps changing the colors to the ones that you have and cleaning it up so that the logo part doesn't look wonky might be good enough? What do you think?

**Comment by jjcarstens** [comment]
Sounds good to me. We can also do a few different versions and pick which one to display based on `:io.columns` (which is what I've been doing with mine)

I'd be interested to see what the block one looks like a little cleaned up

**Comment by fhunleth** [comment]
Here's another attempt at a block one:

image

It needs colors. I ended up writing a program to convert png files to Unicode blocks, but I don't have a way of colorizing it except manually. And there are a ton of ways of improving it - slightly frustrated that I couldn't find something to do this that wasn't so tied to another framework that it was hard to use.

If one of yours with the "NERVES" text is < 60 characters wide, I'm thinking that it is "good enough".

**Comment by fhunleth** [comment]
Here's what it looks like now:

image

At this point, I'm thinking that this is pretty good.

**Review by jjcarstens — APPROVED** [review]
Love it! 😍 :shipit:

**Review by mobileoverlord — APPROVED** [review]

**Pull request merged**
