### PR TITLE
Suggest to use `:console` logger backend for :host

### PR DESCRIPTION
**Pull request by pojiro**
I think that it's natural to use :console logger backend when developing Nerves on host machine isn't it?

### CODE REVIEW

**Comment by fhunleth** [comment]
That's a really good idea! I'm not sure why we hadn't changed this earlier. 

Could you move the logger configuration to `target.exs`, though? Nothing needs to be done in `host.exs` since the defaults will get you the console logger.

**Comment by pojiro** [comment]
Done!

**Comment by fhunleth** [comment]
Looks good to me. Thanks for the PR!

**Comment by pojiro** [comment]
I'm sorry, my PR broke the CI. I dig it and fix it asap.

**Comment by pojiro** [comment]
I fixed it by PR #243, :pray: .

**Pull request merged**
