### PR TITLE
Bootstrap Mix on Application.start

### PR DESCRIPTION
**Pull request by mobileoverlord**
This is safe and concise.

When patching into `loadconfig` we need a call that will not raise so if nerves_bootstrap is not installed, `archive.check` can produce a more meaningful error

This is the style proposed with this PR. I think its the best option.
```elixir
  def project do
    [
      # ...
      archives: [nerves_bootstrap: "~> 0.6"],
      aliases: ["loadconfig": [&bootstrap/1]],
    ]
  end

  def bootstrap(args) do
    Application.start(:nerves_bootstrap)
    Mix.Task.run("loadconfig", args)
  end
```

### CODE REVIEW

**Comment by fhunleth** [comment]
This isn't producing an error message for me. The `Applications.start/1` just returns an `{:error, {'no such file or directory', 'nerves_bootstrap.app'}}` which is silently ignored.

**Comment by mobileoverlord** [comment]
If you uninstall the archive, it should make its way through to tell you that you need to install it. If you are running on the current installed version, this will silently fail.

**Comment by fhunleth** [comment]
I'm confused as to how that works. What if I did:
```
  def project do
    [
      # ...
      aliases: ["loadconfig": [&bootstrap/1]],
    ]
  end

  def bootstrap(args) do
    Application.start(:frank_bootstrap)
    Mix.Task.run("loadconfig", args)
  end
```
Are you saying that it would tell me to install `:frank_bootstrap`?

**Comment by mobileoverlord** [comment]
`archive.check` triggers based off the 
```elixir
archives: [nerves_bootstrap: "~> 0.6"]
```
not by the alias to try to start the app

**Comment by mobileoverlord** [comment]
The archive check has been there from a long time ago, so its not part of the install / update instructions. This just lets it safely run through the sequence up to `archive.check` so it can produce that error. So, Application.start silently failing is desired.

**Comment by fhunleth** [comment]
I see: `Application.start(:nerves_bootstrap)` has the side effect of modifying the `:aliases` list.

**Comment by fhunleth** [comment]
So, does that strike you as slightly evil?

Is there a way to do something like this:
```
  defp bootstrap(args) do
    Code.ensure_loaded(Nerves.Bootstrap) == {:module, Nerves.Bootstrap} &&  Nerves.Bootstrap.update_aliases()
    Mix.Task.run("loadconfig", args)
  end
```

**Comment by mobileoverlord** [comment]
I added a blurb to the new project generator about what happens when you start nerves_bootstrap

**Pull request merged**
