### PR TITLE
v1.10.0 release

### PR DESCRIPTION
**Pull request by mobileoverlord**

### CODE REVIEW

**Review by jjcarstens — APPROVED** [review]

**Review by fhunleth — APPROVED** [review]

**Comment by fhunleth** [comment]
@mobileoverlord The `shoehorn` update version update turned out to be wrong, so I fixed it in PR #167. The OSD32MP1 update and Nerves system version bumps were fine, so I cherry-picked that commit and merged to `main`. The only other thing I did was update `ex_doc` so that whatever docs get pushed to hex.pm are the latest style. I think this is ready to go.

**Comment by fhunleth** [comment]
Before we release, we should update `:nerves_pack` and force the newer version to workaround the optional OTP applications getting listed out of order in the OTP release start script with Elixir 1.11 (not a 1.11 issue. I don't know how we got lucky with 1.10).

**Review by fhunleth — CHANGES_REQUESTED** [review]
Temporarily withdrawing my approval until we get a chance to discuss how we'll resolve OTP app ordering issue.

**Comment by fhunleth** [comment]
Rebased so that this is can be merged again.

I think this is ready to go. The OTP app ordering issue isn't being fixed any time soon, but I think we understand the issue and have fixed the main library causing pain (`nerves_pack`).

As for Elixir 1.11, the only fix that hasn't been released yet is https://github.com/elixir-lang/elixir/commit/3f3e987a233edf1cf47bc97b76b26b3813d1450f, and most of my projects seem to be working with out it.

**Review by fhunleth — APPROVED** [review]

**Pull request merged**
